# server:
#     port: 8201

spring:
    application:
        name: expense-tracker

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/expense_tracker
        username: root
        password: password